# Generated by Django 5.2.4 on 2025-07-14 04:59

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMoneyInputs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('UPI', models.IntegerField()),
                ('cash', models.IntegerField()),
                ('cards', models.IntegerField()),
                ('date', models.DateField(default=datetime.date.today, unique=True)),
                ('in_total', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Dealers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_name', models.CharField(max_length=50)),
                ('party_slug', models.SlugField(blank=True)),
                ('GST_num', models.CharField(blank=True, max_length=15, null=True)),
                ('opening_balance', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Tasklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(blank=True, max_length=100)),
                ('task_date', models.DateField(auto_now=True)),
                ('task_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_img', models.ImageField(upload_to='bill_images')),
                ('bill_date', models.DateField(blank=True, null=True)),
                ('bill_amount', models.FloatField()),
                ('dealer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accountancy.dealers')),
            ],
            options={
                'verbose_name': 'Bills',
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('payment_amount', models.FloatField()),
                ('payment_method', models.CharField(max_length=50)),
                ('dealer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountancy.dealers')),
            ],
            options={
                'verbose_name': 'Payments',
            },
        ),
    ]
