# Generated by Django 5.2.4 on 2026-09-08 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountancy', '0002_create_default_business'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('code_hash', models.CharField(max_length=64)),
                ('purpose', models.CharField(choices=[('verify_email', 'Email verification'), ('password_reset', 'Password reset')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['email', 'purpose'], name='accountancy_email_d3381f_idx')],
            },
        ),
    ]
