# Generated by Django 5.2.4 on 2026-09-10 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountancy', '0003_otpcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpayment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('card', 'Card'), ('cheque', 'Cheque'), ('bank_transfer', 'Bank transfer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('card', 'Card'), ('cheque', 'Cheque'), ('bank_transfer', 'Bank transfer')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('method__in', ['cash', 'upi', 'card', 'cheque', 'bank_transfer'])), name='payment_method_valid'),
        ),
    ]
